name: Bookmark
author: "@katydecorah"
description: "Bookmark websites to a YAML file."
runs:
  using: "node16"
  main: dist/index.js

inputs:
  fileName:
    description: "The filename to save your bookmarks."
    default: "_data/bookmarks.json"
