name: Bookmark
author: "@katydecorah"
description: "Bookmark websites to a JSON file."
runs:
  using: "node16"
  main: dist/index.js

inputs:
  fileName:
    description: "The filename to save your bookmarks."
    default: "_data/bookmarks.json"
  getImage:
    description: "Export the URL's `image` to download later and set `image` property."
    default: "true"
